### ISSUE TITLE
Please revert sign handling to what was used in version 1.0.9

### ISSUE THREAD

**Issue by freedomlives** [RBEGamer/HLK-LD2450#8]
I am using the latest firmware (according to HLK tool app for Android) - Firmware 2.04.23101915 - and also tried the experimental Firmware 2.02.23090617. I am not sure what the one who created the issue #5 was using, but version 1.0.9 of this library correctly processes the data.

Here is output from 1.1.0 (moving my hand from left to right of the sensor):
`TARGET ID=1 X=-32705mm, Y=-32402mm, SPEED=68cm/s, RESOLUTION=360mm, DISTANCE=46038mm, VALID=1
TARGET ID=1 X=260mm, Y=-32519mm, SPEED=51cm/s, RESOLUTION=360mm, DISTANCE=32520mm, VALID=1`
**The values are simply implausible - it cannot detect at a distance of 32.5m...**

Whereas 1.0.9 looks right:
`17:50:48.813 > TARGET ID=1 X=-230mm, Y=226mm, SPEED=68cm/s, RESOLUTION=360mm, DISTANCE=322mm, VALID=1
17:50:49.283 > TARGET ID=1 X=215mm, Y=251mm, SPEED=17cm/s, RESOLUTION=360mm, DISTANCE=330mm, VALID=1`

The datasheet is clear about the odd format the sensor sends, where positive values have a highest bit set 1, and negative set as 0, and then the necessary conversion needed. 1.0.9 correctly implemented the conversions needed for this to work.

<img width="1056" height="393" alt="Image" src="https://github.com/user-attachments/assets/6d96d1f6-52f4-4370-89f3-7034625a694f" />

<img width="1014" height="513" alt="Image" src="https://github.com/user-attachments/assets/5332ff00-ac6f-4478-9c89-de6d953cfb5b" />

**Comment by RBEGamer** [comment]
Done - please test with real hardware

**Comment by E3D3** [comment]
I have the same experience as @freedomlives when using the basic example. Version 1.1.0 shows distances > 32 meters but version 1.0.9 seems to work okay.

And thanks for sharing this library.

**Comment by RBEGamer** [comment]
Still ? I rewoked the changes back so v1.0.9.
Can you check it ?

**Comment by E3D3** [comment]
In v1.1.0 only the X-value seems to be okay now but the Y-value, DISTANCE and SPEED are still wrong.
Maybe you forgot to subtract 2^15 from the Y-value ?

**Comment by srjbhx** [comment]
Now I reverted the lib to 1.0.9 and everything is working as it should. And I have extra LD2450 for spare.
